//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfectial.Presentation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perfectial.Presentation.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string AccountControllerLoginErrorMessage {
            get {
                return ResourceManager.GetString("AccountControllerLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string AccountControllerVerifyCodeErrorMessage {
            get {
                return ResourceManager.GetString("AccountControllerVerifyCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string AddPhoneNumberViewModelPhoneNumber {
            get {
                return ResourceManager.GetString("AddPhoneNumberViewModelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePasswordViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ChangePasswordViewModelConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordViewModelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordViewModelNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ChangePasswordViewModelNewPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelNewPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ExternalLoginConfirmationViewModelEmail {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgotPasswordViewModelEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginViewModelEmail {
            get {
                return ResourceManager.GetString("LoginViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModelPassword {
            get {
                return ResourceManager.GetString("LoginViewModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LoginViewModelRememberBrowserCookie {
            get {
                return ResourceManager.GetString("LoginViewModelRememberBrowserCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string ManageControllerVerifyPhoneNumberErrorMessage {
            get {
                return ResourceManager.GetString("ManageControllerVerifyPhoneNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string RegisterViewModelConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewModelConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterViewModelEmail {
            get {
                return ResourceManager.GetString("RegisterViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterViewModelPassword {
            get {
                return ResourceManager.GetString("RegisterViewModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterViewModelPasswordErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewModelPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ResetPasswordViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ResetPasswordViewModelConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordViewModelConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ResetPasswordViewModelEmail {
            get {
                return ResourceManager.GetString("ResetPasswordViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ResetPasswordViewModelPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ResetPasswordViewModelPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordViewModelPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string SetPasswordViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("SetPasswordViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string SetPasswordViewModelConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("SetPasswordViewModelConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string SetPasswordViewModelNewPassword {
            get {
                return ResourceManager.GetString("SetPasswordViewModelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string SetPasswordViewModelNewPasswordErrorMessage {
            get {
                return ResourceManager.GetString("SetPasswordViewModelNewPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string VerifyCodeViewModelCode {
            get {
                return ResourceManager.GetString("VerifyCodeViewModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string VerifyCodeViewModelRememberBrowser {
            get {
                return ResourceManager.GetString("VerifyCodeViewModelRememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string VerifyPhoneNumberViewModelCode {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberViewModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string VerifyPhoneNumberViewModelPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberViewModelPhoneNumber", resourceCulture);
            }
        }
    }
}
